### ISSUE TITLE
TImeoutError

### ISSUE THREAD

**Issue by frederikhol** [KoenvdStroom/Magister-API-key#2]
Elke keer als ik mijn api key probeer te krijgen krijg ik: TimeoutError: waiting for selector `#password` failed: timeout 30000ms exceeded

zou een van jullie weten wat ik hiermee moet?

ik gebruik de laaste versie van puppeteer en van magister-api-key

Alvast bedankt.

**Comment by KoenvdStroom** [comment]
Hallo,

Welke link gebruik je als je Magister URL?

**Comment by frederikhol** [comment]
https://davinci.magister.net

**Comment by KoenvdStroom** [comment]
Ik heb debug mode toegevoegd, als je 
```javascript
magister.get('url', 'username', 'password', true)
```
gebruikt, dan opent puppeteer in headless = false, en dan kan je zien waar hij vastloopt. 
Ik gok dat magister er lang over doet om je username te checken. Dit kan aan de servers van magister liggen, maar ook aan jouw internet connectie.

**Comment by frederikhol** [comment]
Ja, mijn leerlingnummer wordt ingevuld en daarna blijft het vast staan op het invoeren van het wachtwoord. Zou het mogelijk zijn om een iets langere delay toe te voegen aan dit?

**Comment by KoenvdStroom** [comment]
Die delay is een dingetje van Puppeteer, je kan er zelf naar kijken en deze repo forken om je eigen versie te gebruiken oid.
Laat hij de wachtwoord-input wel zien of komt hij daar simpelweg gewoon niet? Het lijkt me namelijk dat 30s wel lang genoeg zou moeten zijn om die input te laden...

**Comment by frederikhol** [comment]
Ja hij komt wel bij het stuk waar je de wachtwoord input te zien krijgt maar vanaf daar gebeurt er niks meer.

**Comment by KoenvdStroom** [comment]
Vreemd...
Zou ik je code kunnen bekijken? (even je wachtwoord veranderen)
Misschien dat ik dan wat beter begrijp wat er mis gaat...

**Comment by frederikhol** [comment]
const magister = require('magister-api-key');

magister.get('https://davinci.magister.net/', 'leerlingnummer', 'ww', true)

dit is mijn code, doe ik iets verkeerd?

**Comment by KoenvdStroom** [comment]
Nee naar mijn idee doe je niks verkeerd...
Je zou zelf de repo kunnen forken en kijken of je specifiekere debugging kan doen.

**Comment by frederikhol** [comment]
Ik heb het gefixed door je code iets aan te passen:


[index.zip](https://github.com/KoenvdStroom/Magister-API-key/files/6166902/index.zip)
